# Задача
Для данного датасета обучите дерево решений (для обучения используйте массивы с ключами x, y), затем предскажите классы для данных доступных в файле по ключу x_test.

В качестве ответа запишите метку класса - 1 или 0

In [2]:
url = 'https://github.com/bykov-alexei/data-science-course/blob/master/%D0%9C%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B5%20%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B9/train_data.npz?raw=true'

from urllib.request import urlopen
from io import BytesIO
import pandas as pd
import numpy as np
load = BytesIO(urlopen(url).read())
npz = np.load(load)

In [3]:
X = pd.DataFrame(npz['x'])

In [4]:
Y = pd.DataFrame(npz['y'])

In [5]:
x_test = pd.DataFrame(npz['x_test'])

In [6]:
import warnings
warnings.filterwarnings('ignore')

# Дерево решений
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X, Y)
dt.predict(x_test)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [7]:
dt.score(x_test, [1,1,0,1,1,1,0,1,0,1])

0.7

In [8]:
# случайный лес
from sklearn.ensemble import RandomForestClassifier

final_forest = RandomForestClassifier() 
final_forest.fit(X, Y)
final_forest_pred = final_forest.predict_proba(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [9]:
final_forest.predict_proba(x_test)

array([[0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0.4, 0.6],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ]])

In [10]:
final_forest.predict(x_test)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [11]:
final_forest.score(x_test, [1,1,0,1,1,1,0,1,0,1])

0.7

In [18]:
# Дерево решений, замена коррелирующих значений
correlation = 0.9
df = X[X.corr()>correlation].fillna(0)
df_test = x_test[x_test.corr()>correlation].fillna(0)

DTC = DecisionTreeClassifier()
DTC.fit(df, Y)
DTC.predict(df_test)

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [20]:
DTC.score(df_test, [1,1,0,1,1,1,0,1,0,1])

1.0