# Власні значення (числа) та власні вектори.
## Eigenvalues and eigenvectors

[Знаходимо власні значення та власні вектори матриці](#part1)

[Канонічне розкладання матриці](#part2)

Розглянемо довільну квадратну матрицю, наприклад $$A = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix}$$
І помножимо цю матрицю праворуч на який-небудь відповідний стовпець. Мені спало на думку вектор :
$$\bar{b} = \begin{bmatrix}-1 \\1 \end{bmatrix}$$

$$A*\bar{b} = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix} * \begin{bmatrix}-1 \\1 \end{bmatrix} = \begin{bmatrix}-1*(-1) & -6*(1) \\2*(-1) & 6*(1) \end{bmatrix}=\begin{bmatrix}-5 \\4 \end{bmatrix}=\bar{c}$$

In [1]:
# помножимо цю матрицю на вектор за допомогою numpy 
import numpy as np
A = np.array([[-1,-6],[2,6]])
b = np.array([-1,1])
np.dot(A,b) # Out: array([-5,  4])

array([-5,  4])

Начебто нічого примітного - помножили матрицю $A = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix}$ на вектор-стовпець $\bar{b} = \begin{bmatrix}-1 \\1 \end{bmatrix}$ і отримали інший вектор-стовпець $\bar{c} = \begin{bmatrix}-5 \\4 \end{bmatrix}$. Звичайне векторне життя. Але в суспільстві таких векторів існують особливі представники, які мають внутрішній стрижень і не бажають змінювати собі у важкі хвилини.

Помножимо ту ж матрицю на вектор $\bar{u} = \bbox[orange, 8px]{\begin{bmatrix}2 \\-1 \end{bmatrix}}$

$$A*\bar{u} = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix} * \begin{bmatrix}2 \\-1 \end{bmatrix} = \begin{bmatrix}-1*(2) & -6*(-1) \\2*(2) & 6*(-1) \end{bmatrix}=\begin{bmatrix}4 \\-2 \end{bmatrix}=2*\bbox[orange, 8px]{\begin{bmatrix}2 \\-1 \end{bmatrix}}$$

>На останньому кроці винесли константу. Що сталося? В результаті множення матриці на вектор, даний вектор відродився з числовим коефіцієнтом $\lambda=2$: $A\bar{u}=\lambda\bar{u}$

>**Визначення:** ненульовий вектор $\bar{u}$, який при множенні на деяку квадратну матрицю $A$ перетворюється на самого себе з числовим коефіцієнтом $\lambda$, називається **власним вектором** матриці. Число $\lambda$ називають **власним значенням** чи **власним числом** цієї матриці.

In [2]:
u = np.array([2,-1])
np.dot(A,u) # Out: array([4,  -2])

array([ 4, -2])

# Власні значення та власні вектори матриці

<p id='part1'></p>
    
Проведемо дослідження та отримаємо алгоритм, яким потрібно вирішувати це завдання. Люди, які не дуже добре розуміються на математиці (та й які добре) зазвичай у страху чи огиді закривають підручник, коли мова заходить про якийсь доказ чи виведення якоїсь формули. Але це не той випадок – все буде зрозуміло навіть повному чайнику:

##### Приклад

Знайти власні числа та власні вектори матриці $A = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix}$ Перед вами та сама матриця, у якої я вже отримане одне власне значення та один власний вектор. Давайте навчимося добувати їх самостійно:

Позначимо через $\bar{u} = {\begin{bmatrix}x \\y \end{bmatrix}}$ невідомий власний вектор. Тоді матричне рівняння $\lambda=2$: $A\bar{u}=\lambda\bar{u}$ запишеться так:

$$A*\bar{u} = \begin{bmatrix}-1 & -6 \\2 & 6 \end{bmatrix} * \begin{bmatrix}x \\y \end{bmatrix} =\lambda *{\begin{bmatrix}x \\y \end{bmatrix}}$$
У лівій частині за звичайним правилом проведемо матричне множення, у правій частині – внесемо «лямбду»:
$$\begin{bmatrix}-1*(x) & -6*(y) \\2*(x) & 6*(y) \end{bmatrix}={\begin{bmatrix}\lambda *x \\\lambda *y \end{bmatrix}}$$

Дві матриці рівні, якщо рівні відповідні їх елементи. Прирівнюємо відповідні елементи векторів-стовпців та отримуємо однорідну систему лінійних рівнянь:
$$ \left\{ \begin{array}{cl}
-x & -& 6y&=\lambda{x} \\
2x & +& 6y&=\lambda{y}
\end{array} \right.$$
Перенесемо все наліво:
$$ \left\{ \begin{array}{cl}
-x & -& 6y&-\lambda{x}&=0 \\
2x & +& 6y&-\lambda{y}&=0
\end{array} \right.$$
За визначенням, власний вектор не може бути нульовим $\bar{u} = {\begin{bmatrix}x \\y \end{bmatrix}}\neq{\begin{bmatrix}0 \\0 \end{bmatrix}}$, тому нас не влаштовує тривіальне рішення системи. Якщо ж однорідна система має ненульове рішення, її рівняння лінійно залежні і визначник матриці дорівнює нулю:
$$\begin{bmatrix}-1-\lambda & -6 \\2 & 6- \lambda \end{bmatrix}=0$$
Це так зване характеристичне рівняння матриці, коріння якого є власними числами цієї матриці.

Насправді, зазвичай, потрібно розписувати докладний висновок формули – цілком достатньо керуватися формальним алгоритмом, і розв'язання завдання можна розпочати приблизно так:

>Спочатку **знайдемо власні значення**
Складемо характеристичне рівняння. Дивимося на вихідну матрицю та записуємо її визначник, віднімаючи при цьому «лямбду» з чисел головної діагоналі:
$$\begin{bmatrix}-1-\lambda & -6 \\2 & 6- \lambda \end{bmatrix}=0$$
Розкриємо визначник і розв'яжемо квадратне рівняння:
$$(-1-\lambda)*(6-\lambda)-2*(-6)=0$$
$$\lambda^2 - 5\lambda -6+12=0$$
$$\lambda^2 - 5\lambda +6=0$$
$$D=25-24=1; \sqrt{D}=1$$
$$\lambda_{1} = \frac{5-1}{2}=2$$
$$\lambda_{2} = \frac{5+1}{2}=3$$

Таким чином, власні значення $\lambda_{1} =2, \lambda_{2} =3$. Бажано розташовувати їх у порядку зростання, хоча це не важливо.

>Тепер **знайдемо власні вектори**
У цьому прикладі отримані різні власні числа і кожному їх відповідає свої власні вектори.
Розглянемо власне число $\lambda_{1} =2$ і підставимо значення  $\lambda_{1} =2\lambda = 2$ однорідну систему рівнянь
$$ \left\{ \begin{array}{cl}
(-1-\lambda)x & -& 6y=0 \\
2x & +& (6-\lambda)y=0
\end{array} \right. \implies   \left\{ \begin{array}{cl}
-3x & -& 6y=0 \\
2x & +& 4y=0
\end{array} \right.$$
Для запису системи доцільно запам'ятати формальний прийом: подумки або на чернетці підставляємо $\lambda_{1} =2\lambda = 2$ у визначник 
$$\begin{bmatrix}-1-\lambda & -6 \\2 & 6- \lambda \end{bmatrix}=0 \implies  \begin{bmatrix}-3 & -6 \\2 & 4 \end{bmatrix}=0$$
Це і є коефіцієнти системи. З обох рівнянь випливає:
$$\left\{ \begin{array}{cl}
-3x & -& 6y=0 \\
2x & +& 4y=0
\end{array} \right. \implies x = -2y$$
Отже, у нашому розпорядженні є вираз , і, надаючи змінної $y$ (або $x$) довільні значення, ми отримуємо безліч **власних векторів**
Всі вони будуть колінеарними один одному, і тому нам достатньо вказати один із них. Зазвичай намагаються вибрати «красивий» вектор – щоб його «іксова» координата була позитивною, цілою та мінімальною, а $y$ не дробовим.

In [3]:
# знайдемо власні значення та власні вектори за допомогою numpy:
 
# Обчислення власних значень та власних векторів ермітової або речової симетричної матриці.
eigh_val, eigh_vec = np.linalg.eigh(A)

display(eigh_val) # власні значення
eigh_vec # власні вектори

array([-1.53112887,  6.53112887])

array([[-0.96649965,  0.25666794],
       [ 0.25666794,  0.96649965]])

# Канонічне розкладання матриці
## (Спектральне розкладання матриці)

<p id='part2'></p>
    
Що це таке?

Якщо власні вектори матриці $A$ утворюють базис, то її можна відобразити як: $A = UDU^{-1}$, де $U$ – матриця складена з координат власних векторів, $D$– діагональна матриця з відповідними власними числами. $U^{-1}$- зворотна матриця $U$
Таке розкладання матриці називають **канонічним чи діагональним**.

In [4]:
U = eigh_vec # власні вектори
U_1 = np.linalg.inv(eigh_vec) # - зворотна матриця
D = np.diag(eigh_val) # діагональна матриця з відповідними власними числами

In [5]:
np.dot(U, np.dot(D, U_1)) # A

array([[-1.,  2.],
       [ 2.,  6.]])

In [6]:
A # не відповідає !!! ?

array([[-1, -6],
       [ 2,  6]])

In [7]:
# Обчислення власних значень та правих власних векторів.
eigh_vals, eigh_vecs = np.linalg.eig(A)

In [8]:
np.dot(eigh_vecs, np.dot(np.diag(eigh_vals), np.linalg.inv(eigh_vecs))) # Відповідає!!!!

array([[-1., -6.],
       [ 2.,  6.]])

# Приклад 2

In [9]:
X = np.array([
    [1,2,-1],
    [2,2,5],
    [-1,5,-3],])
X

array([[ 1,  2, -1],
       [ 2,  2,  5],
       [-1,  5, -3]])

In [10]:
v, w = np.linalg.eigh(X)

In [11]:
S = w.T
S

array([[-0.24709   ,  0.5304425 , -0.81091139],
       [ 0.92927297, -0.10742791, -0.3534275 ],
       [-0.27458749, -0.84088643, -0.46638151]])

In [12]:
S.T

array([[-0.24709   ,  0.92927297, -0.27458749],
       [ 0.5304425 , -0.10742791, -0.84088643],
       [-0.81091139, -0.3534275 , -0.46638151]])

In [13]:
D = np.diag(v)
D

array([[-6.5753629 ,  0.        ,  0.        ],
       [ 0.        ,  1.14911837,  0.        ],
       [ 0.        ,  0.        ,  5.42624453]])

In [14]:
np.dot(np.dot(S.T, D),S)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])